apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nestjs-app"},"name":"nestjs-app","namespace":"nestjs"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nestjs-app"}},"template":{"metadata":{"labels":{"app":"nestjs-app"}},"spec":{"containers":[{"args":["dist/main.js"],"command":["node"],"env":[{"name":"PORT","value":"3000"},{"name":"MY_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"OTEL_SERVICE_NAME","value":"nestjs-app"},{"name":"OTEL_METRICS_EXPORTER","value":"otlp"},{"name":"OTEL_LOGS_EXPORTER","value":"otlp"},{"name":"OTEL_LOG_LEVEL","value":"debug"},{"name":"OTEL_TRACES_EXPORTER","value":"otlp"},{"name":"OTEL_EXPORTER_OTLP_TRACES_ENDPOINT","value":"http://otel-collector.observability.svc.cluster.local:4318/v1/traces"},{"name":"OTEL_EXPORTER_OTLP_LOGS_ENDPOINT","value":"http://otel-collector.observability.svc.cluster.local:4318/v1/logs"},{"name":"OTEL_EXPORTER_OTLP_METRICS_ENDPOINT","value":"http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://otel-collector.observability.svc.cluster.local:4318"},{"name":"OTEL_EXPORTER_OTLP_PROTOCOL","value":"http"},{"name":"NODE_ENV","value":"production"},{"name":"OTEL_EXPORTER_OTLP_INSECURE","value":"true"},{"name":"OTEL_EXPORTER_OTLP_HEADERS","value":"Authorization=LumigoToken t_f8f7b905da964eef89261"},{"name":"OTEL_SDK_DISABLED","value":"false"},{"name":"OTEL_TRACES_SAMPLER","value":"parentbased_always_on"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.name=nestjs-app,deployment.environment=production"}],"image":"barrysolomon/nest-opentelemetry-example:latest","imagePullPolicy":"Always","name":"nestjs-app","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"256m","memory":"512Mi"}}}]}}}}
  creationTimestamp: "2025-03-23T13:27:05Z"
  generation: 8
  labels:
    app: nestjs-app
  name: nestjs-app
  namespace: nestjs
  resourceVersion: "5028"
  uid: f0a3e94d-01fe-4c19-8ba7-ad8232f959f2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nestjs-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-23T08:32:34-06:00"
      creationTimestamp: null
      labels:
        app: nestjs-app
    spec:
      containers:
      - args:
        - dist/main.js
        command:
        - node
        env:
        - name: PORT
          value: "3000"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OTEL_SERVICE_NAME
          value: nestjs-app
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_LOG_LEVEL
          value: debug
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318/v1/traces
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318/v1/logs
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318/v1/metrics
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http
        - name: NODE_ENV
          value: production
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: Authorization=LumigoToken t_f8f7b905da964eef89261
        - name: OTEL_SDK_DISABLED
          value: "false"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_always_on
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=nestjs-app,deployment.environment=production
        image: barrysolomon/nest-opentelemetry-example:latest
        imagePullPolicy: Always
        name: nestjs-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 256m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data-volume
          mountPath: /usr/src/app/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: nestjs-data-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-23T13:27:08Z"
    lastUpdateTime: "2025-03-23T13:27:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-23T13:27:05Z"
    lastUpdateTime: "2025-03-23T14:32:37Z"
    message: ReplicaSet "nestjs-app-55bf974588" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
