apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: observability
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000  
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus 