{
 "title": "NestJS Application Metrics",
 "tags": [
  "nestjs",
  "opentelemetry"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Calls (Total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "otel_api_calls_total{job=\"otel-collector\"}"
    }
   ]
  },
  {
   "title": "API Calls Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(otel_api_calls_total{job=\"otel-collector\"}[1m])"
    }
   ]
  },
  {
   "title": "API Calls by Endpoint",
   "type": "timeseries",
   "description": "Total API calls to the application, specific to the Hello endpoint",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "otel_api_calls_total{job=\"otel-collector\", exported_endpoint=\"getHello\"}"
    }
   ]
  }
 ]
}