apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: observability
data:
  sidecar.ini: |-
    [panels]
    disable_sanitize_html = true
    
    [security]
    allow_embedding = true
    
    [server]
    domain = grafana.example.com
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true 