---
apiVersion: v1
kind: Namespace
metadata:
  name: nestjs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  namespace: nestjs
  labels:
    app: nestjs-app

spec:
  replicas: 1  # Increased replicas for redundancy
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app

    spec:
      containers:
        - name: nestjs-app
          image: barrysolomon/nest-opentelemetry-example:latest
          imagePullPolicy: Always  # Ensures the latest image is pulled every deployment
          ports:
            - containerPort: 3000
              protocol: TCP

          env:
            - name: PORT
              value: "3000"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: OTEL_SERVICE_NAME
              value: "nestjs-app"

            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
              
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"

            - name: OTEL_LOG_LEVEL
              value: "debug"

            - name: OTEL_TRACES_EXPORTER
              value: "otlp"

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318"

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"

            - name: NODE_ENV
              value: "production"

            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: otel-collector.observability.svc.cluster.local:4317
              
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"

            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "Authorization=LumigoToken t_f8f7b905da964eef89261"

            - name: OTEL_SDK_DISABLED
              value: "false"

            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_always_on"

          command: ["node"]
          #args: ["-r", "@lumigo/opentelemetry/sync", "dist/main.js"]
          args: ["dist/main.js"]

          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 3000
      #   fsGroup: 2000
      # restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
  namespace: nestjs
  labels:
    app: nestjs-app
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
