---
apiVersion: v1
kind: Namespace
metadata:
  name: nestjs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  namespace: nestjs
  labels:
    app: nestjs-app

spec:
  replicas: 1  # Increased replicas for redundancy
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app

    spec:
      containers:
        - name: nestjs-app
          image: barrysolomon/nest-opentelemetry-example:latest
          imagePullPolicy: Always  # Ensures the latest image is pulled every deployment
          ports:
            - containerPort: 3000
              protocol: TCP

          env:
            - name: PORT
              value: "3000"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: NODE_ENV
              value: "production"

            - name: ENABLE_OTEL
              value: "true"

            - name: OTEL_SERVICE_NAME
              value: "nestjs-app"

            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
              
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"

            - name: OTEL_LOG_LEVEL
              value: "debug"

            - name: OTEL_TRACES_EXPORTER
              value: "otlp"

            # # # Setting specific endpoints for each signal type using HTTP
            # - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            # #   value: "ga-otlp.lumigo-tracer-edge.golumigo.com"
            #   value: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
            # #  value: "http://lumigo-lumigo-operator-telemetry-proxy-service.lumigo-system.svc.cluster.local/v1/traces"

            # - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
            # #   value: "https://ga-otlp.lumigo-tracer-edge.golumigo.com"
            #   value: "http://otel-collector.observability.svc.cluster.local:4318/v1/logs"
            # #  value: "http://lumigo-lumigo-operator-telemetry-proxy-service.lumigo-system.svc.cluster.local/v1/logs"

            # - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            # #   value: "https://ga-otlp.lumigo-tracer-edge.golumigo.com"
            #   value: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
            # #  value: "http://lumigo-lumigo-operator-telemetry-proxy-service.lumigo-system.svc.cluster.local/v1/metrics"
              
            # # Keeping this for backward compatibility
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            # #  value: "https://ga-otlp.lumigo-tracer-edge.golumigo.com"
            # #  value: "http://otel-collector.observability.svc.cluster.local:4318"
            # #  value: "http://lumigo-lumigo-operator-telemetry-proxy-service.lumigo-system.svc.cluster.local"
              
            # - name: OTEL_EXPORTER_OTLP_PROTOCOL
            #   #value: "https"
            #   value: "http"
              
            # - name: OTEL_EXPORTER_OTLP_INSECURE
            #   #value: "false"
            #   value: "true"

            # - name: OTEL_EXPORTER_OTLP_HEADERS
            #   value: "Authorization=LumigoToken t_f8f7b905da964eef89261"

            - name: OTEL_SDK_DISABLED
              value: "false"

            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_always_on"
              
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=nestjs-app,deployment.environment=production"

          command: ["node"]
          args: ["dist/main.js"]

          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
  namespace: nestjs
  labels:
    app: nestjs-app
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 3000
      name: metrics
  type: LoadBalancer
