apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nestjs-app
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - nestjs
  selector:
    matchLabels:
      app: nestjs-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s 