apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
            include_metadata: true
            transport: "tcp"
            max_recv_msg_size_mib: 64
            max_concurrent_streams: 1000
            read_buffer_size: 512_000
            write_buffer_size: 512_000
            keepalive:
              server_parameters:
                max_connection_age: 30s
                max_connection_age_grace: 5s
                time: 5s
                timeout: 5s
                max_connection_idle: 10s
              enforcement_policy:
                min_time: 5s
                permit_without_stream: true
          http:
            endpoint: "0.0.0.0:4318"
            cors:
              allowed_origins: ["*"]
            include_metadata: true
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              static_configs:
                - targets: ['localhost:8888']
              metric_relabel_configs:
                - action: labeldrop
                  regex: ^target_info.*

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1000
      memory_limiter:
        limit_mib: 1000
        spike_limit_mib: 200
        check_interval: 30s
      resource:
        attributes:
          - key: loki.resource.labels
            value: service.name,service.namespace
            action: insert

    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 1
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "otel"
        const_labels:
          label1: value1
        send_timestamps: true
        metric_expiration: 180m
      logging:
        loglevel: debug
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
        default_labels_enabled:
          exporter: true
          job: true

    service:
      telemetry:
        logs:
          level: "debug"
          development: true
          encoding: "console"
        metrics:
          level: "detailed"
          address: "0.0.0.0:8888"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [debug, loki, logging]