apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: observability
data:
  prometheus-additional.yaml: |
    - job_name: 'otel-collector-prometheus'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
        - targets:
          - otel-collector.observability.svc.cluster.local:8889 