server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:                     # ✅ Make sure this is present
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317  # ✅ Bind to all interfaces
        http:
          endpoint: 0.0.0.0:4318  # ✅ Bind to all interfaces
    jaeger:
      protocols:
        grpc:
        thrift_http:
    zipkin:
    opencensus:

ingester:
  trace_idle_period: 30s
  max_block_duration: 5m
  complete_block_timeout: 1m

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

overrides:
  per_tenant_override_config: /etc/overrides.yaml
