{
 "title": "NestJS App Metrics (Simple)",
 "tags": [
  "nestjs",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_count{service_name=\"nestjs-app\"}[1m])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_sum{service_name=\"nestjs-app\"}[1m]) / rate(http_server_duration_count{service_name=\"nestjs-app\"}[1m])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_count{service_name=\"nestjs-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{service_name=\"nestjs-app\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}