{
 "title": "OpenTelemetry / Collector",
 "tags": [ "prometheus-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Batch Send Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "otelcol_processor_batch_batch_send_size"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "otelcol_processor_memory_limiter_current_usage_bytes"
    }
   ]
  },
  {
   "title": "Batch Send Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "otelcol_processor_batch_batch_send_size_bytes"
    }
   ]
  },
  {
   "title": "Memory Spike Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "otelcol_processor_memory_limiter_spike_limit_bytes"
    }
   ]
  }
 ]
}