apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-prometheus
  namespace: observability
  labels:
    release: prometheus
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: prometheus
  selector:
    matchLabels:
      app: otel-collector 